In [ ]:
import pandas as pd
import numpy as np
cards = pd.read_csv('main.csv')
cards

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [ ]:
cards.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [ ]:
cards.tail()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [ ]:
cards.sum()

Team                          CroatiaCzech RepublicDenmarkEnglandFranceGerma...
Goals                                                                        76
Shots on target                                                             274
Shots off target                                                            399
Shooting Accuracy             51.9%41.9%50.0%50.0%37.9%47.8%30.7%43.0%25.0%3...
% Goals-to-shots              16.0%12.9%20.0%17.2%6.5%15.6%19.2%7.5%4.1%5.2%...
Total shots (inc. Blocked)                                                  879
Hit Woodwork                                                                 20
Penalty goals                                                                 3
Penalties not scored                                                          1
Headed goals                                                                 22
Passes                                                                    28214
Passes completed                                                          23478
Passing Accuracy              76.9%78.1%83.3%80.6%87.2%87.4%76.7%83.9%88.7%8...
Touches                                                                   41267
Crosses                                                                     915
Dribbles                                                                    837
Corners Taken                                                               345
Tackles                                                                    1094
Clearances                                                                 1382
Interceptions                                                              1017
Clearances off line                                                         5.0
Clean Sheets                                                                 17
Blocks                                                                      201
Goals conceded                                                               76
Saves made                                                                  194
Saves-to-shots ratio          81.3%60.1%66.7%88.1%54.6%62.6%65.1%74.1%70.6%6...
Fouls Won                                                                   847
Fouls Conceded                                                              890
Offsides                                                                    130
Yellow Cards                                                                119
Red Cards                                                                     3
Subs on                                                                     174
Subs off                                                                    174
Players Used                                                                276
dtype: object

In [ ]:
cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        16 non-null     object
 1   Goals                       16 non-null     int64
 2   Shots on target             16 non-null     int64
 3   Shots off target            16 non-null     int64
 4   Shooting Accuracy           16 non-null     object
 5   % Goals-to-shots            16 non-null     object
 6   Total shots (inc. Blocked)  16 non-null     int64
 7   Hit Woodwork                16 non-null     int64
 8   Penalty goals               16 non-null     int64
 9   Penalties not scored        16 non-null     int64
 10  Headed goals                16 non-null     int64
 11  Passes                      16 non-null     int64
 12  Passes completed            16 non-null     int64
 13  Passing Accuracy            16 non-null     object
 14  Touches                     16 non-null     int64
 15  Crosses                     16 non-null     int64
 16  Dribbles                    16 non-null     int64
 17  Corners Taken               16 non-null     int64
 18  Tackles                     16 non-null     int64
 19  Clearances                  16 non-null     int64
 20  Interceptions               16 non-null     int64
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64
 23  Blocks                      16 non-null     int64
 24  Goals conceded              16 non-null     int64
 25  Saves made                  16 non-null     int64
 26  Saves-to-shots ratio        16 non-null     object
 27  Fouls Won                   16 non-null     int64
 28  Fouls Conceded              16 non-null     int64
 29  Offsides                    16 non-null     int64
 30  Yellow Cards                16 non-null     int64
 31  Red Cards                   16 non-null     int64
 32  Subs on                     16 non-null     int64
 33  Subs off                    16 non-null     int64
 34  Players Used                16 non-null     int64
dtypes: float64(1), int64(29), object(5)
memory usage: 4.5+ KB

In [ ]:
assign = cards[['Team', 'Yellow Cards', 'Red Cards']]

In [ ]:
assign

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [ ]:
assign.sort_values(by=['Red Cards', 'Yellow Cards'], ascending = False)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

In [ ]:
cards.describe()

,Goals,Shots on target,Shots off target,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,...,Goals conceded,Saves made,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
count,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.0000,16.000000,16.000000,16.000000,...,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.00000,16.00000,16.000000
mean,4.750000,17.125000,24.937500,54.937500,1.250000,0.187500,0.0625,1.375000,1763.375000,1467.375000,...,4.750000,12.125000,52.937500,55.625000,8.125000,7.437500,0.187500,10.87500,10.87500,17.250000
std,2.886751,10.582218,10.680005,26.065223,1.612452,0.403113,0.2500,1.024695,906.177898,827.580721,...,1.983263,4.573474,22.915697,18.973227,4.910872,3.265348,0.403113,3.53789,3.53789,1.527525
min,1.000000,7.000000,10.000000,27.000000,0.000000,0.000000,0.0000,0.000000,851.000000,606.000000,...,1.000000,6.000000,25.000000,30.000000,2.000000,4.000000,0.000000,7.00000,7.00000,15.000000
25%,2.750000,9.750000,18.000000,36.500000,0.000000,0.000000,0.0000,0.750000,1190.750000,951.500000,...,3.000000,9.750000,35.750000,44.500000,4.000000,5.000000,0.000000,8.50000,8.50000,16.000000
50%,4.500000,13.000000,23.500000,44.000000,1.000000,0.000000,0.0000,1.500000,1522.000000,1211.500000,...,5.000000,11.000000,45.500000,51.000000,7.500000,6.500000,0.000000,10.50000,10.50000,17.000000
75%,5.250000,22.000000,32.250000,68.750000,2.000000,0.000000,0.0000,2.000000,1934.750000,1546.500000,...,6.000000,13.500000,64.000000,64.750000,11.250000,9.000000,0.000000,12.50000,12.50000,18.250000
max,12.000000,42.000000,45.000000,110.000000,6.000000,1.000000,1.0000,3.000000,4317.000000,3820.000000,...,9.000000,22.000000,102.000000,90.000000,19.000000,16.000000,1.000000,18.00000,18.00000,20.000000